name: Update Specimen

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Swift
              uses: swift-actions/setup-swift@v2

            - name: Update Specimen Data
              id: compare_shas
              run: |
                swift build -c release
                rm -rf ./Sources/GachaMetaDB/Resources/OUTPUT-HSR.json || true
                rm -rf ./Sources/GachaMetaDB/Resources/OUTPUT-GI.json || true
                .build/release/GachaMetaGenerator -HSRD > ./Sources/GachaMetaDB/Resources/OUTPUT-HSR.json
                .build/release/GachaMetaGenerator -GID > ./Sources/GachaMetaDB/Resources/OUTPUT-GI.json

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: update-gacha-meta-${{ github.run_number }}
                base: main
                title: "Update Specimen"
                body: |
                  This PR updates the gacha meta specimen.
                delete-branch: true
                assignees: ShikiSuen
                reviewers: ShikiSuen
                team-reviewers: |
                  owners
                  maintainers
