name: Update Specimen GI

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: macOS-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Swift
              uses: swift-actions/setup-swift@v2

            - name: Fetch latest commit SHA
              id: latest_sha
              run: echo "::set-output name=sha::$(git ls-remote https://github.com/DimbreathBot/AnimeGameData.git HEAD | cut -f1)"

            - name: Update Specimen Data
              id: compare_shas
              run: |
                swift build -c release
                rm -rf ./Specimen/OUTPUT-GI.json || true
                .build/release/GachaMetaGenerator -GI > ./Specimen/OUTPUT-GI.json

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: update-gacha-meta-${{ github.run_number }}
                base: main
                title: "Update Specimen GI"
                body: |
                  This PR updates the gacha meta and other assets (see update_other_meta.py for details).
                delete-branch: true
                assignees: ShikiSuen
                reviewers: ShikiSuen
                team-reviewers: |
                  owners
                  maintainers
